layout_spectrum: 0.09318996
typography_spectrum: 0.3978495
color:
  saturation: 0.09523342
  lightness: 0.04642019
  brandStrength: 0.2753388
  rhythmicContrast: 0.5541673
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: Sobrepeso y Obesidad
